### PR TITLE
Add compare funcs

### PR DESCRIPTION
**Pull request by michaelmcd18**

### CODE REVIEW

**Comment by michaelmcd18** [comment]
buildCompare diff from `review`
Screenshot 2024-05-28 at 7 58 25 AM

**Comment by michaelmcd18** [comment]
diff from compareFigures in `review`:
Screenshot 2024-05-28 at 7 59 06 AM

**Comment by michaelmcd18** [comment]
diff from compareLocal in `review`:
Screenshot 2024-05-28 at 8 00 23 AM

**Comment by michaelmcd18** [comment]
diff for compareTables in `review`:
Screenshot 2024-05-28 at 8 00 50 AM

**Comment by michaelmcd18** [comment]
diff for compareModified from `review`:
Screenshot 2024-05-28 at 8 02 24 AM

**Comment by andersone1** [comment]
- [X] buildCompare.R
- [ ] compareFigures.R
- [ ] compareLocal.R
- [ ] compareModified.R
- [ ] compareTables.R
- [ ] demoRepo.R

**Review by andersone1 — APPROVED** [review]

**Pull request merged**
